version: '3'
services:
  server_http:
    restart: always
    build: ./server_HTTP
    ports:
    - "8080:8080"
    networks:
    - server-tier

  client_mobile:
    restart: on-failure
    build: ./client_mobile
    ports:
    - "8081:8081"
    networks:
    - server-tier

networks:
  server-tier:
    driver: bridge
