version: '3'
services:
        serv:
                restart: always
                build: ./serv
                ports:
                - "4242:80"
                networks:
                - serv-tier

networks:
        serv-tier:
                driver: bridge
volumes:
  db-data:
