version: '3'
services:
  server_http:
    restart: always
    build: ./server_HTTP/
    ports:
      - "8080:8080"
    networks:
      - server-tier

  client_mobile:
    restart: on-failure
    build: ./client_mobile/
    depends_on:
      - server_http
    networks:
      - server-tier
    volumes:
      - client-data:/public_shared/

  client_website:
    restart: always
    build: ./client_website/
    depends_on:
      - server_http
      - client_mobile
    ports:
      - "8081:8081"
    networks:
      - server-tier
    volumes:
      - client-data:/public_shared/

networks:
  server-tier:
    driver: bridge

volumes:
  client-data:
