version: '3'
services:
        serv:
                restart: always
                build: ./serv
                networks:
                - serv-tier
        web:
                build: ./web/area_web

networks:
        serv-tier:
                driver: bridge
volumes:
  db-data:
