version: '3'
services:
  server_http:
    restart: always
    build: ./server_HTTP/
    ports:
      - "8080:8080"
    networks:
      - server-tier

  client_mobile:
    restart: on-failure
    build: ./client_mobile/
    ports:
      - "8081:8081"
    networks:
      - server-tier
    volumes:
      - client-data:/client_mobile/

  client_website:
    restart: always
    build: ./client_website/
    ports:
      - "8081:8081"
    networks:
      - server-tier
    volumes:
      - client-data:/client_website/

networks:
  server-tier:
    driver: bridge

volumes:
  client-data: